# Generated by Django 4.2.4 on 2023-10-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creating', models.DateField(blank=True, null=True)),
                ('date_formation', models.DateField(blank=True, null=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
                ('moderator', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'application',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('doctor', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'appointment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('student_group', models.CharField(blank=True, max_length=10, null=True)),
                ('id_appl', models.OneToOneField(db_column='id_appl', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.application')),
            ],
            options={
                'db_table': 'students',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AppApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_appl', models.OneToOneField(db_column='id_appl', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.application')),
                ('id_appoint', models.OneToOneField(db_column='id_appoint', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.appointment')),
            ],
            options={
                'db_table': 'app_app',
                'managed': True,
            },
        ),
    ]
