# Generated by Django 4.2.4 on 2023-10-03 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appapp',
            name='id_appl',
            field=models.ForeignKey(db_column='id_appl', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.application'),
        ),
        migrations.AlterField(
            model_name='appapp',
            name='id_appoint',
            field=models.ForeignKey(db_column='id_appoint', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.appointment'),
        ),
        migrations.AlterField(
            model_name='students',
            name='id_appl',
            field=models.ForeignKey(db_column='id_appl', on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.application'),
        ),
    ]
