# Generated by Django 4.2.4 on 2023-10-07 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_appapp_id_appl_alter_appapp_id_appoint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='id_appl',
        ),
        migrations.AddField(
            model_name='application',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', default=0, on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.students'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appapp',
            name='id_appl',
            field=models.ForeignKey(db_column='id_appl', on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.application'),
        ),
        migrations.AlterField(
            model_name='appapp',
            name='id_appoint',
            field=models.ForeignKey(db_column='id_appoint', on_delete=django.db.models.deletion.CASCADE, to='bmstu_lab.appointment'),
        ),
    ]
