# Generated by Django 4.2.4 on 2023-12-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_alter_appointment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='was',
            field=models.BooleanField(default=False, verbose_name='Был ли на приёме?'),
        ),
    ]
