# Generated by Django 4.2.4 on 2024-01-31 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_application_was'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='was',
        ),
        migrations.AddField(
            model_name='appapp',
            name='was',
            field=models.BooleanField(default=False, verbose_name='Был ли на приёме?'),
        ),
    ]
