# Generated by Django 4.2.4 on 2023-10-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0003_remove_students_id_appl_application_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
